pipeline:
  name: harness-jhttp
  identifier: harnessjhttp
  projectIdentifier: githubharnessjhttp
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.mshahatgithub
        repoName: jhttp
        build: <+input>
  stages:
    - stage:
        name: built-jhttp
        identifier: builtjhttp
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: RunTests
                  name: run-test
                  identifier: runtest
                  spec:
                    language: Java
                    buildTool: Maven
                    args: clean test
                    runOnlySelectedTests: true
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "**/*.xml"
                    enableTestSplitting: false
